[package]
cjc-version = "1.0.0"
name = "registry"
description = "nothing here"
version = "0.1.0"
target-dir = ""
output-type = "static"
compile-option = ""
override-compile-option = ""
link-option = ""
package-configuration = {}

[dependencies]
